# Generated by Django 3.2.9 on 2022-03-20 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock_level',
        ),
    ]
