# Generated by Django 3.2.9 on 2022-03-20 15:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_stock_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_level',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
