# Generated by Django 3.2.9 on 2022-03-20 15:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_productinventory_stock_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinventory',
            name='stock_level',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
