# Generated by Django 3.2.9 on 2022-03-20 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20220320_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock_level',
        ),
        migrations.AddField(
            model_name='productinventory',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
